import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsDateString,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Min,
} from 'class-validator';

export class AILocationDto {
  @ApiProperty({
    description: 'Location ID',
    example: 'fa5c272f-4e3b-43f0-830d-9c16a4c7408f',
  })
  @IsUUID('4')
  locationId!: string;

  @ApiProperty({
    description: 'Order of this location in the itinerary (1-based)',
    example: 1,
  })
  @IsNumber()
  @Min(1)
  @Type(() => Number)
  order!: number;

  @ApiPropertyOptional({
    description:
      'Travel distance from previous location to this one (km). Accepts both AI format (distanceFromPrevious) and entity format (travelDistanceKm)',
    example: 2.4,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  travelDistanceKm?: number;

  @ApiPropertyOptional({
    description:
      'Distance from previous location (AI format - from PersonalJourneyResponse)',
    example: 2.4,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  distanceFromPrevious?: number;

  @ApiPropertyOptional({
    description:
      'Travel time from previous location to this one (minutes). Accepts both AI format (estimatedTravelTimeMinutes) and entity format (travelDurationMinutes)',
    example: 7,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  travelDurationMinutes?: number;

  @ApiPropertyOptional({
    description:
      'Estimated travel time from previous location (AI format - from PersonalJourneyResponse)',
    example: 7,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  estimatedTravelTimeMinutes?: number;

  @ApiPropertyOptional({
    description: 'Optional note for this location',
    example: 'Ăn sáng tại quán nổi tiếng gần đây',
  })
  @IsString()
  @IsOptional()
  notes?: string;
}

export class CreateItineraryFromAIDto {
  @ApiProperty({
    description: 'Itinerary title',
    example: 'Khám phá Sài Gòn - Lịch trình AI',
  })
  @IsString()
  @IsNotEmpty()
  title!: string;

  @ApiPropertyOptional({
    description: 'Itinerary description',
    example: 'Lịch trình được tạo tự động bởi AI',
  })
  @IsString()
  @IsOptional()
  description?: string;

  @ApiPropertyOptional({
    description: 'Start date (ISO 8601)',
    example: '2025-11-15',
  })
  @IsDateString()
  @IsOptional()
  startDate?: string;

  @ApiPropertyOptional({
    description: 'End date (ISO 8601)',
    example: '2025-11-17',
  })
  @IsDateString()
  @IsOptional()
  endDate?: string;

  @ApiPropertyOptional({
    description: 'Thumbnail image URL for the itinerary',
    example: 'https://example.com/thumbnail.jpg',
  })
  @IsString()
  @IsOptional()
  thumbnailUrl?: string;

  @ApiPropertyOptional({
    description:
      'Array of location IDs in wishlist (AI suggested or user-provided)',
    type: [String],
    example: [
      'fa5c272f-4e3b-43f0-830d-9c16a4c7408f',
      'b735a6d3-12ab-4c57-9f4b-b222251d6b74',
    ],
  })
  @IsArray()
  @IsUUID('4', { each: true })
  @IsOptional()
  locationWishlist?: string[];

  @ApiProperty({
    description:
      'Ordered locations generated by AI, including per-leg travel metrics',
    type: [AILocationDto],
  })
  @IsArray()
  @Type(() => AILocationDto)
  locations!: AILocationDto[];

  @ApiPropertyOptional({
    description:
      'Total travel distance across all segments (km) as provided by AI/FE',
    example: 12.7,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  totalDistanceKm?: number;

  @ApiPropertyOptional({
    description:
      'Total travel time across all segments (minutes) as provided by AI/FE. Accepts both AI format (estimatedTotalTimeMinutes) and entity format (totalTravelMinutes)',
    example: 45,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  totalTravelMinutes?: number;

  @ApiPropertyOptional({
    description:
      'Estimated total travel time (AI format - from PersonalJourneyResponse)',
    example: 45,
  })
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  estimatedTotalTimeMinutes?: number;

  @ApiProperty({
    description:
      'AI reasoning from the itinerary generator. Context or explanation for the generated route',
    example: 'Ưu tiên các điểm gần nhau để tiết kiệm thời gian di chuyển…',
  })
  @IsString()
  @IsNotEmpty()
  reasoning!: string;

  @ApiProperty({
    description: 'AI tips for the journey',
    type: [String],
    example: ['Đi sớm để tránh kẹt xe', 'Mang theo nước uống'],
  })
  @IsArray()
  @IsString({ each: true })
  tips!: string[];

  @ApiPropertyOptional({
    description: 'Original prompt used for AI generation',
  })
  @IsString()
  @IsOptional()
  prompt?: string;
}
