create table tag
(
    id                      integer generated by default as identity
        constraint "PK_8e4052373c579afc1471f526760"
            primary key,
    created_at              timestamp with time zone default now()                          not null,
    updated_at              timestamp with time zone default now()                          not null,
    deleted_at              timestamp with time zone,
    group_name              varchar(100)             default 'USER_TYPE'::character varying not null,
    display_name            varchar(255)                                                    not null,
    display_name_normalized varchar(255)                                                    not null,
    color                   varchar(50)                                                     not null,
    icon                    varchar(10)                                                     not null,
    is_selectable           boolean                  default true                           not null
);

alter table tag
    owner to ubl_user;

create table ranks
(
    id         uuid                     default uuid_generate_v4() not null
        constraint "PK_7620a297228c6e9ed28e9fd07e4"
            primary key,
    name       varchar(50)                                         not null,
    min_points integer                                             not null,
    max_points integer,
    icon       varchar(255),
    created_at timestamp with time zone default now()              not null,
    updated_at timestamp with time zone default now()              not null
);

alter table ranks
    owner to ubl_user;

create table accounts
(
    id            uuid                     default uuid_generate_v4()        not null
        constraint "PK_5a7a02c20412299d198e097a8fe"
            primary key,
    first_name    varchar(255)                                               not null,
    last_name     varchar(255)                                               not null,
    email         varchar(255)                                               not null
        constraint "UQ_ee66de6cdc53993296d1ceb8aa0"
            unique,
    phone_number  varchar(255)                                               not null,
    password      varchar(255)                                               not null,
    created_at    timestamp with time zone default now()                     not null,
    updated_at    timestamp with time zone default now()                     not null,
    avatar_url    varchar,
    cover_url     varchar,
    has_onboarded boolean                  default false                     not null,
    role          varchar(50)              default 'USER'::character varying not null,
    is_locked     boolean                  default false                     not null
);

alter table accounts
    owner to ubl_user;

create table reacts
(
    id          uuid                     default uuid_generate_v4() not null
        constraint "PK_e9a4e287e70372a267d7f363a12"
            primary key,
    entity_id   uuid                                                not null,
    entity_type varchar                                             not null,
    type        varchar(50)                                         not null,
    author_id   uuid                                                not null
        constraint "FK_14d2d62990b6da117a37dfbe6bb"
            references accounts
            on delete cascade,
    created_at  timestamp with time zone default now()              not null,
    updated_at  timestamp with time zone default now()              not null
);

alter table reacts
    owner to ubl_user;

create table posts
(
    content     text                                                not null,
    type        varchar(50)                                         not null,
    rating      integer,
    created_at  timestamp with time zone default now()              not null,
    updated_at  timestamp with time zone default now()              not null,
    image_urls  text[]                   default '{}'::text[]       not null,
    author_id   uuid                                                not null
        constraint "FK_312c63be865c81b922e39c2475e"
            references accounts
            on delete cascade,
    location_id uuid,
    event_id    uuid,
    visibility  varchar(50),
    post_id     uuid                     default uuid_generate_v4() not null
        constraint "PK_e55cc433639d0e21c3dbf637bce"
            primary key,
    is_verified boolean                  default false              not null,
    is_hidden   boolean                  default false              not null
);

alter table posts
    owner to ubl_user;

create table comments
(
    comment_id uuid                     default uuid_generate_v4() not null
        constraint "PK_eb0d76f2ca45d66a7de04c7c72b"
            primary key,
    content    text                                                not null,
    created_at timestamp with time zone default now()              not null,
    updated_at timestamp with time zone default now()              not null,
    author_id  uuid                                                not null
        constraint "FK_e6d38899c31997c45d128a8973b"
            references accounts
            on delete cascade,
    post_id    uuid                                                not null
        constraint "FK_259bf9825d9d198608d1b46b0b5"
            references posts
            on delete cascade
);

alter table comments
    owner to ubl_user;

create table business
(
    account_id      uuid                                                          not null
        constraint "PK_8ef555f5592ce1a2e91538490b9"
            primary key
        constraint "FK_8ef555f5592ce1a2e91538490b9"
            references accounts
            on delete cascade,
    avatar          varchar(255),
    website         varchar(255)                                                  not null,
    name            varchar(255)                                                  not null,
    address_line    varchar(255)                                                  not null,
    address_level_1 varchar(255)                                                  not null,
    address_level_2 varchar(255)                                                  not null,
    description     text                                                          not null,
    licenses        jsonb,
    is_active       boolean                  default true                         not null,
    created_at      timestamp with time zone default now()                        not null,
    updated_at      timestamp with time zone default now()                        not null,
    status          varchar(50)              default 'PENDING'::character varying not null,
    admin_notes     text,
    email           varchar(255)                                                  not null,
    phone           varchar(255)                                                  not null,
    category        varchar(50)              default 'OTHER'::character varying   not null
);

alter table business
    owner to ubl_user;

create table location_requests
(
    id                            uuid                     default uuid_generate_v4()                         not null
        constraint "PK_686d7e8dc8f8e890802773acb3c"
            primary key,
    created_at                    timestamp with time zone default now()                                      not null,
    updated_at                    timestamp with time zone default now()                                      not null,
    created_by                    uuid                                                                        not null
        constraint "FK_37e7a587a37eda806ff784be9ce"
            references accounts,
    type                          varchar(50)              default 'BUSINESS_OWNED'::character varying        not null,
    name                          varchar(255)                                                                not null,
    description                   text                                                                        not null,
    latitude                      numeric(10, 8)                                                              not null,
    longitude                     numeric(11, 8)                                                              not null,
    radius_meters                 integer                  default 0                                          not null,
    address_line                  varchar(255)                                                                not null,
    address_level_1               varchar(100)                                                                not null,
    address_level_2               varchar(100)                                                                not null,
    location_image_urls           text[],
    location_validation_documents jsonb,
    status                        varchar(50)              default 'AWAITING_ADMIN_REVIEW'::character varying not null,
    processed_by                  uuid
        constraint "FK_7a78f26c6b3465458a3536a156a"
            references accounts,
    admin_notes                   text
);

alter table location_requests
    owner to ubl_user;

create table location_request_tags
(
    id                  integer generated by default as identity
        constraint "PK_2c8f4cf541e7756c7197a4480f7"
            primary key,
    created_at          timestamp with time zone default now() not null,
    updated_at          timestamp with time zone default now() not null,
    location_request_id uuid                                   not null
        constraint "FK_f27774a54ca631d478a6f49ea77"
            references location_requests,
    tag_id              integer                                not null
        constraint "FK_a1b81fadbc1558f76ccfa28f96a"
            references tag
);

alter table location_request_tags
    owner to ubl_user;

create table locations
(
    id                         uuid                     default uuid_generate_v4()                     not null
        constraint "PK_7cc1c9e3853b94816c094825e74"
            primary key,
    created_at                 timestamp with time zone default now()                                  not null,
    updated_at                 timestamp with time zone default now()                                  not null,
    updated_by                 uuid
        constraint "FK_931f4ee58838aca7e7726fc8773"
            references accounts,
    business_id                uuid
        constraint "FK_556c5be9ef36f88fc6ce79a4a9a"
            references business,
    ownership_type             varchar(50)              default 'OWNED_BY_BUSINESS'::character varying not null,
    name                       varchar(255)                                                            not null,
    description                text                                                                    not null,
    latitude                   numeric(10, 8)                                                          not null,
    longitude                  numeric(11, 8)                                                          not null,
    radius_meters              integer                  default 0                                      not null,
    address_line               varchar(255)                                                            not null,
    address_level_1            varchar(100)                                                            not null,
    address_level_2            varchar(100)                                                            not null,
    image_url                  text[],
    is_visible_on_map          boolean                  default false                                  not null,
    geom                       geography(Point, 4326),
    source_location_request_id uuid
        constraint "REL_91b2b7e81df9517b64c587368e"
            unique
        constraint "FK_91b2b7e81df9517b64c587368ed"
            references location_requests
);

alter table locations
    owner to ubl_user;

create table location_tags
(
    id          integer generated by default as identity
        constraint "PK_57989b24c832284ce74cac3d40b"
            primary key,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    deleted_at  timestamp with time zone,
    location_id uuid                                   not null
        constraint "FK_3cdc38e4182b966b78f63ac3796"
            references locations,
    tag_id      integer                                not null
        constraint "FK_babe64d29c3a647c887f9e553eb"
            references tag
);

alter table location_tags
    owner to ubl_user;

create table location_booking_config
(
    location_id                      uuid                                   not null
        constraint "PK_e01555279354b8ba95a8e6ce791"
            primary key
        constraint "FK_e01555279354b8ba95a8e6ce791"
            references locations,
    created_at                       timestamp with time zone default now() not null,
    updated_at                       timestamp with time zone default now() not null,
    created_by                       uuid
        constraint "FK_31b8e5e3a3a10feccf10d33b5fa"
            references accounts,
    allow_booking                    boolean                  default false not null,
    base_booking_price               numeric(10, 2)                         not null,
    currency                         varchar(3)                             not null,
    min_booking_duration_minutes     integer                                not null,
    max_booking_duration_minutes     integer                                not null,
    min_gap_between_bookings_minutes integer                                not null
);

alter table location_booking_config
    owner to ubl_user;

create table location_opening_hours
(
    id          integer generated by default as identity
        constraint "PK_355c68a390119f806a215f225f4"
            primary key,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    location_id uuid                                   not null
        constraint "FK_a00603ce5a61a3c48f2c7ac338b"
            references locations,
    day_of_week varchar(20)                            not null,
    start_time  time                                   not null,
    end_time    time                                   not null
);

alter table location_opening_hours
    owner to ubl_user;

create unique index "IDX_a70e4d84fac8e1d4c132030a28"
    on location_opening_hours (location_id, day_of_week);

create table location_analytics
(
    id              uuid          default uuid_generate_v4() not null
        constraint "PK_ac5f12d37737d5766c80856c573"
            primary key,
    location_id     uuid                                     not null
        constraint "UQ_b4be960cac8c92bdc4896c3df4f"
            unique
        constraint "FK_b4be960cac8c92bdc4896c3df4f"
            references locations
            on delete cascade,
    total_posts     bigint        default '0'::bigint        not null,
    total_check_ins bigint        default '0'::bigint        not null,
    total_reviews   integer       default 0                  not null,
    average_rating  numeric(3, 2) default '0'::numeric       not null,
    created_at      timestamp with time zone                 not null,
    updated_at      timestamp with time zone                 not null
);

alter table location_analytics
    owner to ubl_user;

create index "IDX_8414141966619c4947d2f51a70"
    on locations using gist (geom);

create table user_profiles
(
    account_id         uuid              not null
        constraint "PK_8639a49961767b871b05d5d9386"
            primary key
        constraint "FK_8639a49961767b871b05d5d9386"
            references accounts,
    dob                timestamp with time zone,
    bio                text,
    rank_id            uuid
        constraint "FK_c7433ad797d6727dc9dcfadf7d2"
            references ranks,
    rank               varchar(50),
    points             integer default 0 not null,
    ranking_point      integer default 0 not null,
    total_achievements integer default 0 not null,
    total_check_ins    integer default 0 not null,
    total_blogs        integer default 0 not null,
    total_reviews      integer default 0 not null,
    total_followers    integer default 0 not null,
    total_following    integer default 0 not null,
    tag_scores         jsonb   default '{}'::jsonb
);

alter table user_profiles
    owner to ubl_user;

create table check_ins
(
    id                    uuid                     default uuid_generate_v4() not null
        constraint "PK_fac7f27bc829a454ad477c13f62"
            primary key,
    created_at            timestamp with time zone default now()              not null,
    updated_at            timestamp with time zone default now()              not null,
    user_profile_id       uuid                                                not null
        constraint "FK_7a4fabf52821fcaf4aa81aca612"
            references user_profiles,
    location_id           uuid                                                not null
        constraint "FK_ac0bd157c6c6931072cd88c576d"
            references locations,
    latitude_at_check_in  double precision                                    not null,
    longitude_at_check_in double precision                                    not null
);

alter table check_ins
    owner to ubl_user;

create table creator_profile
(
    account_id   uuid          not null
        constraint "PK_896798b8dd5ed816ed9bdbd8662"
            primary key
        constraint "FK_896798b8dd5ed816ed9bdbd8662"
            references accounts,
    display_name varchar(555)  not null,
    description  text          not null,
    email        varchar(255)  not null,
    phone        varchar(255)  not null,
    avatar_url   varchar(2048) not null,
    cover_url    varchar(2048) not null,
    type         varchar(100)  not null,
    social       jsonb
);

alter table creator_profile
    owner to ubl_user;

create table user_tags
(
    id         integer generated by default as identity
        constraint "PK_deef7519b4b9995a9ecc3f7e611"
            primary key,
    account_id uuid    not null
        constraint "FK_2161843f47eded3e4712a531598"
            references accounts,
    tag_id     integer not null
        constraint "FK_082dadc021168fef6e1afd42ad7"
            references tag
);

alter table user_tags
    owner to ubl_user;

create table follows
(
    follow_id   uuid                     default uuid_generate_v4() not null
        constraint "PK_216b46abae15bf5368d90a1116a"
            primary key,
    follower_id uuid                                                not null
        constraint "FK_54b5dc2739f2dea57900933db66"
            references accounts
            on delete cascade,
    entity_id   uuid                                                not null,
    entity_type varchar(50)                                         not null,
    created_at  timestamp with time zone default now()              not null
);

alter table follows
    owner to ubl_user;

create table favorite_locations
(
    favorite_id uuid                     default uuid_generate_v4() not null
        constraint "PK_0aac47b338991fa57df3a33fbfb"
            primary key,
    account_id  uuid                                                not null
        constraint "FK_ae42a4eb91bddffc1a4bfcaee45"
            references accounts,
    location_id uuid                                                not null
        constraint "FK_b1f2a34b850133461d10345a2cc"
            references locations,
    created_at  timestamp with time zone default now()              not null
);

alter table favorite_locations
    owner to ubl_user;

create table tag_category
(
    id                integer generated by default as identity
        constraint "PK_3249fd70734f41f513a1d5d3ef7"
            primary key,
    name              varchar(100)                                       not null
        constraint "UQ_f48a9fe1f705a7c2a60856d395a"
            unique,
    description       text,
    color             varchar(50),
    icon              varchar(50),
    applicable_types  jsonb                    default '["USER"]'::jsonb not null,
    tag_score_weights jsonb                    default '{}'::jsonb       not null,
    created_at        timestamp with time zone default now()             not null,
    updated_at        timestamp with time zone default now()             not null
);

alter table tag_category
    owner to ubl_user;

create table fcm_token
(
    id          integer generated by default as identity
        constraint "PK_ec8f7ff07f44545126442edd9e7"
            primary key,
    token       varchar(555)                           not null
        constraint "UQ_443f8d9334e75b1e2ec1312d114"
            unique,
    device_info varchar(255),
    user_id     uuid                                   not null
        constraint "FK_260df94c40407731f062dceee02"
            references accounts,
    "createdAt" timestamp with time zone default now() not null
);

alter table fcm_token
    owner to ubl_user;

create table push_notification
(
    id         integer generated by default as identity
        constraint "PK_b7e0210528850d5f548629ed593"
            primary key,
    created_at timestamp with time zone default now()                       not null,
    type       varchar(50)                                                  not null,
    payload    jsonb                                                        not null,
    to_user_id uuid                                                         not null
        constraint "FK_03f99e8edd88ff428c236e5b56a"
            references accounts,
    status     varchar(50)              default 'UNSEEN'::character varying not null
);

alter table push_notification
    owner to ubl_user;

create table public_file
(
    id             integer generated by default as identity
        constraint "PK_bf2f5ba5aa6e3453b04cb4e4720"
            primary key,
    file_name      varchar(1000)                                                         not null,
    file_size_mb   numeric                                                               not null,
    file_mime_type varchar(100)                                                          not null,
    file_url       varchar(2000),
    status         varchar(50)              default 'AWAITING_UPLOAD'::character varying not null,
    created_by     uuid                                                                  not null
        constraint "FK_f28c725c0e93449742574c74cef"
            references accounts,
    created_at     timestamp with time zone default now()                                not null
);

alter table public_file
    owner to ubl_user;

create table reward_points
(
    id     uuid default uuid_generate_v4() not null
        constraint "PK_b04907622cbfc5e492056cfc72c"
            primary key,
    type   varchar(50)                     not null,
    points integer                         not null
);

alter table reward_points
    owner to ubl_user;

create table points_history
(
    id               uuid                     default uuid_generate_v4() not null
        constraint "PK_9c1159eab3bdfcc3e11f647e8f7"
            primary key,
    user_id          uuid                                                not null,
    points           integer                                             not null,
    transaction_type varchar(50)                                         not null,
    description      text,
    reference_id     uuid,
    balance_before   integer                                             not null,
    balance_after    integer                                             not null,
    created_at       timestamp with time zone default now()              not null
);

alter table points_history
    owner to ubl_user;

create table location_missions
(
    id          uuid                     default uuid_generate_v4() not null
        constraint "PK_1013a829b8c8744ed31e817dac5"
            primary key,
    location_id uuid                                                not null
        constraint "FK_ab9c0cdc6b16d561a17628736a3"
            references locations,
    title       varchar                                             not null,
    description varchar                                             not null,
    target      integer                                             not null,
    start_date  timestamp with time zone                            not null,
    end_date    timestamp with time zone                            not null,
    reward      integer                                             not null,
    image_urls  text[]                   default '{}'::text[]       not null,
    created_at  timestamp with time zone default now()              not null,
    updated_at  timestamp with time zone default now()              not null
);

alter table location_missions
    owner to ubl_user;

create table location_vouchers
(
    id                  uuid                     default uuid_generate_v4()          not null
        constraint "PK_36a66b8ae6c9778f74d24d9aafa"
            primary key,
    location_id         uuid                                                         not null
        constraint "FK_760c393927e7725eb6397071a13"
            references locations,
    title               varchar                                                      not null,
    description         varchar                                                      not null,
    voucher_code        varchar(255)                                                 not null,
    image_url           text,
    price_point         integer                  default 0                           not null,
    max_quantity        integer                  default 0                           not null,
    user_redeemed_limit integer                  default 0                           not null,
    voucher_type        varchar(50)              default 'public'::character varying not null,
    start_date          timestamp with time zone                                     not null,
    end_date            timestamp with time zone                                     not null,
    created_at          timestamp with time zone default now()                       not null,
    updated_at          timestamp with time zone default now()                       not null
);

alter table location_vouchers
    owner to ubl_user;

create table user_mission_progresses
(
    id              uuid default uuid_generate_v4() not null
        constraint "PK_b95160531f4cc3782c362d8b036"
            primary key,
    user_profile_id uuid                            not null
        constraint "FK_3ea3f7b4428eeaeb0f27cefcd6a"
            references user_profiles,
    mission_id      uuid                            not null
        constraint "FK_3aaf690c18e96965c826c21e352"
            references location_missions,
    progress        integer                         not null,
    completed       boolean                         not null
);

alter table user_mission_progresses
    owner to ubl_user;

create table location_mission_logs
(
    id                       uuid                     default uuid_generate_v4() not null
        constraint "PK_6672f17fcb877e193efe985c846"
            primary key,
    user_mission_progress_id uuid                                                not null
        constraint "FK_e239282583684ddb8b271984000"
            references user_mission_progresses,
    image_urls               text[]                   default '{}'::text[]       not null,
    created_at               timestamp with time zone default now()              not null
);

alter table location_mission_logs
    owner to ubl_user;

create table one_time_qr_codes
(
    id                uuid      default uuid_generate_v4() not null
        constraint "PK_ee6111b9ea631158516699415e4"
            primary key,
    qr_code_data      text                                 not null,
    qr_code_url       text                                 not null,
    location_id       uuid                                 not null
        constraint "FK_06712973f7e29e0258da9f50f27"
            references locations,
    business_owner_id uuid                                 not null
        constraint "FK_941d436dd6c861ea0ab680b18e3"
            references user_profiles,
    scanned_by        uuid
        constraint "FK_2ad8376ae5c9ef3d754f4124651"
            references user_profiles,
    scanned_at        timestamp,
    expires_at        timestamp                            not null,
    is_used           boolean   default false              not null,
    reference_id      varchar(255),
    created_at        timestamp default now()              not null,
    updated_at        timestamp default now()              not null
);

comment on column one_time_qr_codes.reference_id is 'ID của đơn hàng hoặc giao dịch';

alter table one_time_qr_codes
    owner to ubl_user;

create table user_location_profiles
(
    id               uuid                     default uuid_generate_v4() not null
        constraint "PK_f359cda5ae531cc3f0142c6d068"
            primary key,
    location_id      uuid                                                not null
        constraint "FK_3c30ea9000e5c4ac28b14c310d5"
            references locations,
    user_profile_id  uuid                                                not null
        constraint "FK_72535bcef5a64b968fdbd2e3ac9"
            references user_profiles,
    total_points     integer                                             not null,
    available_points integer                                             not null,
    created_at       timestamp with time zone default now()              not null,
    updated_at       timestamp with time zone default now()              not null
);

alter table user_location_profiles
    owner to ubl_user;

create table user_location_voucher_exchange_histories
(
    id                uuid                     default uuid_generate_v4() not null
        constraint "PK_17c32bf47a4a953029f0450fb26"
            primary key,
    voucher_id        uuid                                                not null
        constraint "FK_7c096be30a0992db5f0dcfb932d"
            references location_vouchers,
    user_profile_id   uuid                                                not null
        constraint "FK_dd14d1d40b6c1bc7d1d82765cd9"
            references user_profiles,
    point_spent       integer                                             not null,
    user_voucher_code varchar(255)                                        not null
        constraint "UQ_c4750800cfb55d4b735f3332718"
            unique,
    used_at           timestamp with time zone,
    created_at        timestamp with time zone default now()              not null
);

alter table user_location_voucher_exchange_histories
    owner to ubl_user;

create table wallets
(
    id                 uuid                     default uuid_generate_v4()        not null
        constraint "PK_8402e5df5a30a229380e83e4f7e"
            primary key,
    owned_by           uuid
        constraint "REL_8f6d4c5dd321215adf352f5424"
            unique
        constraint "FK_8f6d4c5dd321215adf352f5424f"
            references accounts,
    wallet_type        varchar(20)              default 'USER'::character varying not null,
    created_at         timestamp with time zone default now()                     not null,
    updated_at         timestamp with time zone default now()                     not null,
    balance            numeric(12, 2)           default '0'::numeric              not null,
    locked_balance     numeric(12, 2)           default '0'::numeric              not null,
    currency           varchar(3)                                                 not null,
    total_transactions integer                  default 0                         not null,
    is_locked          boolean                  default false                     not null,
    created_by         uuid                                                       not null,
    updated_by         uuid
);

alter table wallets
    owner to ubl_user;

create table wallet_transactions
(
    id                    uuid                     default uuid_generate_v4()           not null
        constraint "PK_5120f131bde2cda940ec1a621db"
            primary key,
    created_at            timestamp with time zone default now()                        not null,
    source_wallet_id      uuid                                                          not null
        constraint "FK_84263e661ddf3f749c9e8ad6faf"
            references wallets,
    destination_wallet_id uuid                                                          not null
        constraint "FK_89402e882a001e34c6c2d142160"
            references wallets,
    amount                numeric(12, 2)                                                not null,
    currency              varchar(3)                                                    not null,
    type                  varchar(55)                                                   not null,
    status                varchar(20)              default 'PENDING'::character varying not null,
    note                  varchar(255)
);

alter table wallet_transactions
    owner to ubl_user;

create table wallet_external_transactions
(
    id                           uuid                     default uuid_generate_v4()           not null
        constraint "PK_42918707a85b12dce21c98a63c4"
            primary key,
    created_at                   timestamp with time zone default now()                        not null,
    updated_at                   timestamp with time zone default now()                        not null,
    wallet_id                    uuid                                                          not null
        constraint "FK_98b5e412fc1a571465f2eb7344f"
            references wallets,
    provider                     varchar(50),
    provider_transaction_id      varchar(255),
    direction                    varchar(10)                                                   not null,
    amount                       numeric(12, 2)                                                not null,
    currency                     varchar(3)                                                    not null,
    payment_url                  text,
    expires_at                   timestamp with time zone,
    provider_response            jsonb,
    status                       varchar(20)              default 'PENDING'::character varying not null,
    created_by                   uuid                                                          not null
        constraint "FK_06b32b53a50079fcf354c58c1b1"
            references accounts,
    after_finish_action          varchar(50)              default 'NONE'::character varying    not null,
    withdraw_bank_name           varchar(100),
    withdraw_bank_account_number varchar(50),
    withdraw_bank_account_name   varchar(255)
);

alter table wallet_external_transactions
    owner to ubl_user;

create table wallet_external_transaction_timeline
(
    id                uuid                     default uuid_generate_v4()          not null
        constraint "PK_4406e2809dafb94a8c2fc43f88d"
            primary key,
    created_at        timestamp with time zone default now()                       not null,
    transaction_id    uuid                                                         not null
        constraint "FK_3784b0884106b4f866d7d01b1c7"
            references wallet_external_transactions,
    status_changed_to varchar(20),
    action            varchar(100)                                                 not null,
    actor_type        varchar(20)              default 'SYSTEM'::character varying not null,
    actor_id          uuid
        constraint "FK_115d9470a8d417b886ae6246a66"
            references accounts,
    actor_name        varchar(255)                                                 not null,
    note              text,
    metadata          jsonb
);

alter table wallet_external_transaction_timeline
    owner to ubl_user;

create table analytic
(
    analytic_id     uuid          default uuid_generate_v4() not null
        constraint "PK_df796249f6b38da9930248043dd"
            primary key,
    entity_id       uuid,
    entity_type     varchar,
    total_upvotes   integer       default 0                  not null,
    total_downvotes integer       default 0                  not null,
    total_comments  integer       default 0                  not null,
    total_views     integer       default 0                  not null,
    total_reviews   integer       default 0                  not null,
    avg_rating      numeric(3, 2) default '0'::numeric       not null
);

alter table analytic
    owner to ubl_user;

create table scheduled_jobs
(
    id         integer generated by default as identity
        constraint "PK_119312a5470a95ee9c733a5246d"
            primary key,
    created_at timestamp with time zone default now()                        not null,
    updated_at timestamp with time zone default now()                        not null,
    job_type   varchar(255)                                                  not null,
    execute_at timestamp with time zone                                      not null,
    payload    jsonb                                                         not null,
    status     varchar(100)             default 'PENDING'::character varying not null
);

alter table scheduled_jobs
    owner to ubl_user;

create index "IDX_0a870b42a8c32bab34f6f14686"
    on scheduled_jobs (execute_at, status);

create table location_bookings
(
    id                        uuid                     default uuid_generate_v4()             not null
        constraint "PK_bc9cebbc6ac4c777fa26e0be147"
            primary key,
    created_at                timestamp with time zone default now()                          not null,
    updated_at                timestamp with time zone default now()                          not null,
    account_id                uuid                                                            not null
        constraint "FK_c7036be6afff76d7d7916afa1ad"
            references accounts,
    booking_object            varchar(100)             default 'FOR_EVENT'::character varying not null,
    location_id               uuid                                                            not null
        constraint "FK_01f8241681bdaadcfea04de4e44"
            references locations,
    status                    varchar(55)                                                     not null,
    amount_to_pay             numeric                                                         not null,
    referenced_transaction_id uuid
        constraint "FK_c07afe06632de95eaa6cb2813f9"
            references wallet_transactions,
    soft_locked_until         timestamp with time zone,
    scheduled_payout_job_id   integer
        constraint "FK_2bcbc2c9ff2ee88fb5c132cb093"
            references scheduled_jobs,
    paid_out_at               timestamp with time zone
);

alter table location_bookings
    owner to ubl_user;

create table location_booking_dates
(
    id              uuid                     default uuid_generate_v4() not null
        constraint "PK_9e545c3376781bd03045d4c50f3"
            primary key,
    created_at      timestamp with time zone default now()              not null,
    updated_at      timestamp with time zone default now()              not null,
    booking_id      uuid                                                not null
        constraint "FK_409c2565ea5781a39f3811456a1"
            references location_bookings,
    start_date_time timestamp with time zone                            not null,
    end_date_time   timestamp with time zone                            not null
);

alter table location_booking_dates
    owner to ubl_user;

create table event_requests
(
    id                              uuid                     default uuid_generate_v4() not null
        constraint "PK_af5567e19fbb4ffba2ee41fb7a0"
            primary key,
    created_at                      timestamp with time zone default now()              not null,
    updated_at                      timestamp with time zone default now()              not null,
    created_by_id                   uuid                                                not null
        constraint "FK_cb66239b97e3360c9a42cc93ed9"
            references accounts,
    event_name                      varchar(255)                                        not null,
    event_description               text                                                not null,
    expected_number_of_participants integer                                             not null,
    allow_tickets                   boolean                                             not null,
    special_requirements            text                                                not null,
    status                          varchar(55)                                         not null,
    event_validation_documents      jsonb,
    referenced_location_booking_id  uuid
        constraint "REL_c28a9f9b777055b958872b55f0"
            unique
        constraint "FK_c28a9f9b777055b958872b55f01"
            references location_bookings,
    social                          jsonb,
    referenced_event_id             uuid
        constraint "REL_50c0d3082c719c8084e9f04ab3"
            unique
);

alter table event_requests
    owner to ubl_user;

create table event_request_tags
(
    id               uuid                     default uuid_generate_v4() not null
        constraint "PK_c969e08a609839abc426a12386a"
            primary key,
    created_at       timestamp with time zone default now()              not null,
    updated_at       timestamp with time zone default now()              not null,
    event_request_id uuid                                                not null
        constraint "FK_440c30d08f5ebc4a5ed825962e7"
            references event_requests,
    tag_id           integer                                             not null
        constraint "FK_00aee1afb4a8d1317c053ec4a9f"
            references tag
);

alter table event_request_tags
    owner to ubl_user;

create table events
(
    id                          uuid                     default uuid_generate_v4() not null
        constraint "PK_40731c7151fe4be3116e45ddf73"
            primary key,
    created_at                  timestamp with time zone default now()              not null,
    updated_at                  timestamp with time zone default now()              not null,
    account_id                  uuid                                                not null
        constraint "FK_54ec284da4b957748352c8310c8"
            references accounts,
    display_name                varchar(255)                                        not null,
    description                 text                                                not null,
    avatar_url                  varchar(500),
    cover_url                   varchar(500),
    status                      varchar(50)                                         not null,
    start_date                  timestamp with time zone,
    end_date                    timestamp with time zone,
    location_id                 uuid                                                not null
        constraint "FK_fccf31c64ec14a66276e9999730"
            references locations,
    social                      jsonb,
    refund_policy               text,
    terms_and_conditions        text,
    referenced_event_request_id uuid                                                not null
        constraint "REL_36c0297e65401530a8d36132ae"
            unique
        constraint "FK_36c0297e65401530a8d36132ae0"
            references event_requests,
    has_paid_out                boolean                  default false              not null,
    paid_out_at                 timestamp with time zone,
    scheduled_job_id            integer
        constraint "FK_6781580aa1aae5ab27a71199a7d"
            references scheduled_jobs
);

alter table events
    owner to ubl_user;

create table event_tags
(
    id         integer generated by default as identity
        constraint "PK_5864b44fc8c8e55e3540d58c756"
            primary key,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    deleted_at timestamp with time zone,
    tag_id     integer                                not null
        constraint "FK_f80b6bfb86895b578c3083a2e8c"
            references tag,
    event_id   uuid                                   not null
        constraint "FK_640b9db5340d03f53d02a4dca1d"
            references events
);

alter table event_tags
    owner to ubl_user;

alter table event_requests
    add constraint "FK_50c0d3082c719c8084e9f04ab3c"
        foreign key (referenced_event_id) references events;

create table event_ticket
(
    id                       uuid                     default uuid_generate_v4() not null
        constraint "PK_a62752ad96d716bc2cb785ca0bf"
            primary key,
    created_at               timestamp with time zone default now()              not null,
    updated_at               timestamp with time zone default now()              not null,
    created_by               uuid                                                not null
        constraint "FK_753bdba95bab0e7ac5b68e9d3ca"
            references accounts,
    display_name             varchar(255)                                        not null,
    description              text,
    price                    numeric(10, 2)                                      not null,
    currency                 char(3)                  default 'USD'::bpchar      not null,
    image_url                text,
    is_active                boolean                  default true               not null,
    tos                      text,
    total_quantity           integer                  default 0                  not null,
    total_quantity_available integer                  default 0                  not null,
    quantity_reserved        integer                  default 0                  not null,
    sale_start_date          timestamp with time zone                            not null,
    sale_end_date            timestamp with time zone                            not null,
    min_quantity_per_order   integer                  default 1                  not null,
    max_quantity_per_order   integer                  default 5                  not null,
    event_id                 uuid                                                not null
        constraint "FK_061520273ff5fd4e40afd05617e"
            references events
);

alter table event_ticket
    owner to ubl_user;

create table event_ticket_orders
(
    id                        uuid                     default uuid_generate_v4()           not null
        constraint "PK_1cddac05e814180323b0439e8c2"
            primary key,
    order_number              varchar(100)                                                  not null,
    created_at                timestamp with time zone default now()                        not null,
    updated_at                timestamp with time zone default now()                        not null,
    created_by_id             uuid                                                          not null
        constraint "FK_c4bf70b4d35958ef867bfb7bd5f"
            references accounts,
    total_payment_amount      numeric(12, 2)                                                not null,
    currency                  varchar(3)                                                    not null,
    status                    varchar(20)              default 'PENDING'::character varying not null,
    referenced_transaction_id uuid
        constraint "FK_08a38a56b2c3ea5e9e6716a05ec"
            references wallet_transactions,
    event_id                  uuid                                                          not null
        constraint "FK_c40b4e9062df0ed799465aa350d"
            references events
);

alter table event_ticket_orders
    owner to ubl_user;

create table event_ticket_order_details
(
    id              uuid                     default uuid_generate_v4() not null
        constraint "PK_718b8a67a474baee3a28bb25ec2"
            primary key,
    created_at      timestamp with time zone default now()              not null,
    updated_at      timestamp with time zone default now()              not null,
    quantity        integer                                             not null,
    unit_price      numeric(12, 2)                                      not null,
    currency        varchar(3)                                          not null,
    sub_total       numeric(12, 2)                                      not null,
    event_ticket_id uuid                                                not null
        constraint "FK_9bff3459bd7411f8c1f00c7e8b2"
            references event_ticket,
    ticket_order_id uuid                                                not null
        constraint "FK_999640d59404ea88da78dbfdfb8"
            references event_ticket_orders,
    ticket_snapshot jsonb                                               not null
);

alter table event_ticket_order_details
    owner to ubl_user;

create table announcements
(
    id          uuid                     default uuid_generate_v4()            not null
        constraint "PK_b3ad760876ff2e19d58e05dc8b0"
            primary key,
    created_at  timestamp with time zone default now()                         not null,
    updated_at  timestamp with time zone default now()                         not null,
    created_by  uuid
        constraint "FK_40bd4946a00669c5fb7e6d972f0"
            references accounts,
    updated_by  uuid
        constraint "FK_017d8386b86801e9e803fe0c45f"
            references accounts,
    title       varchar(255)                                                   not null,
    description text                                                           not null,
    start_date  timestamp with time zone                                       not null,
    end_date    timestamp with time zone,
    image_url   text,
    type        varchar(50)              default 'LOCATION'::character varying not null,
    location_id uuid
        constraint "FK_5449f1e29556ef586a54735c965"
            references locations,
    event_id    uuid
        constraint "FK_3aa1ff684ac5d194a77c07c3754"
            references events,
    is_hidden   boolean                  default false                         not null
);

alter table announcements
    owner to ubl_user;

create table location_availability
(
    id          integer generated by default as identity
        constraint "PK_4b12a5f4ee13dee3d3b299e0319"
            primary key,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    created_by  uuid                                   not null
        constraint "FK_8cfe46cd8d8fa24a60474cf3908"
            references accounts,
    location_id uuid                                   not null
        constraint "FK_3a154c758c008deb3bb04dd2efc"
            references locations,
    day_of_week varchar(20)                            not null,
    start_time  time                                   not null,
    end_time    time                                   not null
);

alter table location_availability
    owner to ubl_user;

create table event_attendance
(
    id                         uuid                     default uuid_generate_v4() not null
        constraint "PK_f8b37ee4567724d40d0ed38d7f7"
            primary key,
    created_at                 timestamp with time zone default now()              not null,
    updated_at                 timestamp with time zone default now()              not null,
    order_id                   uuid                                                not null
        constraint "FK_9b5e5e4238edcf696806699b42c"
            references event_ticket_orders,
    event_id                   uuid                                                not null
        constraint "FK_f129300b09d62003b8cc80a602c"
            references events,
    status                     varchar(20)                                         not null,
    owner_id                   uuid
        constraint "FK_63d5130610e5f1081045935079a"
            references accounts,
    owner_email                varchar(255),
    owner_phone_number         varchar(255),
    referenced_ticket_order_id uuid                                                not null
        constraint "FK_c311c1b0e4689c8af14059ef7f5"
            references event_ticket_orders,
    ticket_id                  uuid                                                not null
        constraint "FK_806d627d58c06c1046e474a7e32"
            references event_ticket
);

alter table event_attendance
    owner to ubl_user;

create table report_reasons
(
    key          varchar(100)                           not null
        constraint "PK_51068d1794b516412220966a480"
            primary key,
    created_at   timestamp with time zone default now() not null,
    updated_at   timestamp with time zone default now() not null,
    display_name varchar(255)                           not null,
    description  text                                   not null,
    is_active    boolean                  default false not null
);

alter table report_reasons
    owner to ubl_user;

create table reports
(
    id                  uuid                     default uuid_generate_v4() not null
        constraint "PK_d9013193989303580053c0b5ef6"
            primary key,
    target_type         varchar(50)                                         not null,
    target_id           uuid                                                not null,
    reported_reason     varchar(100)                                        not null,
    title               varchar(555)                                        not null,
    description         text,
    attached_image_urls text[]                   default '{}'::text[]       not null,
    status              varchar(50)                                         not null,
    created_at          timestamp with time zone default now()              not null,
    created_by          uuid                                                not null
        constraint "FK_a20814878638f52ffc91005fc42"
            references accounts,
    updated_at          timestamp with time zone default now()              not null,
    last_updated_by     uuid
        constraint "FK_3030fc1810ce3c17f1ff8612918"
            references accounts
);

alter table reports
    owner to ubl_user;

create table address_province
(
    code                 varchar(16)          not null
        constraint "PK_858a97d2423118631af080793f1"
            primary key,
    name                 varchar(248)         not null,
    administrative_level varchar(128)         not null,
    is_visible           boolean default true not null
);

alter table address_province
    owner to ubl_user;

create table address_ward
(
    code                 varchar(16)          not null,
    name                 varchar(128)         not null,
    administrative_level varchar(128)         not null,
    province_code        varchar(16)          not null
        constraint "FK_bf6d741f82fd1916c46dded3a26"
            references address_province,
    is_visible           boolean default true not null,
    constraint "PK_f7249abc9eadec86b1bd8e3694f"
        primary key (code, name)
);

alter table address_ward
    owner to ubl_user;

create table itinerary
(
    id                   uuid                     default uuid_generate_v4()          not null
        constraint "PK_515a9607ae33d4536f40d60f85e"
            primary key,
    user_id              uuid                                                         not null
        constraint "FK_2cc3d068f4f4c703cf5ad034e3b"
            references accounts,
    title                varchar(255)                                                 not null,
    description          text,
    start_date           date,
    end_date             date,
    source               varchar(20)              default 'MANUAL'::character varying not null,
    ai_metadata          jsonb,
    album                text[]                   default '{}'::text[]                not null,
    thumbnail_url        text,
    location_wishlist    uuid[]                   default '{}'::uuid[]                not null,
    total_distance_km    double precision         default '0'::double precision       not null,
    total_travel_minutes integer                  default 0                           not null,
    created_at           timestamp with time zone default now()                       not null,
    updated_at           timestamp with time zone default now()                       not null
);

alter table itinerary
    owner to ubl_user;

create table itinerary_location
(
    id                      uuid                     default uuid_generate_v4() not null
        constraint "PK_81b105ce89427cb7102bc629661"
            primary key,
    itinerary_id            uuid                                                not null
        constraint "FK_3baff8facd0668efeca0f61bc10"
            references itinerary,
    location_id             uuid                                                not null
        constraint "FK_8065128b845832adca8cc7d22a4"
            references locations,
    "order"                 integer                                             not null,
    notes                   text,
    travel_distance_km      double precision,
    travel_duration_minutes integer,
    created_at              timestamp with time zone default now()              not null
);

alter table itinerary_location
    owner to ubl_user;

