-- Create itinerary tables
-- Itinerary: User's saved journey/travel plan
-- ItineraryLocation: Locations in the itinerary with order and activity

-- Create itinerary table
CREATE TABLE IF NOT EXISTS development.itinerary (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  source VARCHAR(20) NOT NULL DEFAULT 'MANUAL', -- 'AI' or 'MANUAL'
  ai_metadata JSONB, -- Store AI reasoning, tips, prompt, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create itinerary_location junction table
CREATE TABLE IF NOT EXISTS development.itinerary_location (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  itinerary_id UUID NOT NULL,
  location_id UUID NOT NULL,
  "order" INTEGER NOT NULL,
  activity TEXT,
  notes TEXT,
  visit_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(itinerary_id, location_id, "order")
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_itinerary_user_id ON development.itinerary(user_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_created_at ON development.itinerary(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_itinerary_location_itinerary_id ON development.itinerary_location(itinerary_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_location_location_id ON development.itinerary_location(location_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_location_order ON development.itinerary_location(itinerary_id, "order");

-- Add comments
COMMENT ON TABLE development.itinerary IS 'User''s saved travel itinerary/journey plans';
COMMENT ON TABLE development.itinerary_location IS 'Locations in an itinerary with order and activity details';
COMMENT ON COLUMN development.itinerary.source IS 'Source of itinerary creation: AI (generated by AI) or MANUAL (user created)';
COMMENT ON COLUMN development.itinerary.ai_metadata IS 'AI-related metadata: reasoning, tips, prompt, model info (only for AI-generated itineraries)';
COMMENT ON COLUMN development.itinerary_location."order" IS 'Order/sequence of location in the itinerary (1, 2, 3, ...)';
COMMENT ON COLUMN development.itinerary_location.activity IS 'Suggested activity at this location';
COMMENT ON COLUMN development.itinerary_location.notes IS 'User''s personal notes for this location';
COMMENT ON COLUMN development.itinerary_location.visit_date IS 'Planned visit date for this location';

-- Grant permissions (commented out - adjust role name if needed)
-- GRANT ALL ON development.itinerary TO your_db_user;
-- GRANT ALL ON development.itinerary_location TO your_db_user;

