export enum AcceptedEventValidationDocuments {
  EVENT_PERMIT = 'EVENT_PERMIT',
  TAX_REGISTRATION = 'TAX_REGISTRATION',
  HEALTH_PERMIT = 'HEALTH_PERMIT',
  LIABILITY_INSURANCE = 'LIABILITY_INSURANCE',
  ORGANIZER_ID = 'ORGANIZER_ID',
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  OTHER = 'OTHER',
}
