export enum AcceptedLocationValidationDocuments {
  LOCATION_REGISTRATION_CERTIFICATE = 'LOCATION_REGISTRATION_CERTIFICATE',
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  TAX_REGISTRATION = 'TAX_REGISTRATION',
  OTHER = 'OTHER',
}
