export enum EmailTemplates {
  WELCOME = './welcome',
  CONFIRM_OTP = './confirm-otp',
  BUSINESS_APPROVED = './business-approved',
  BUSINESS_REJECTED = './business-rejected',
  LOCATION_APPROVED = './location-approved',
  LOCATION_REJECTED = './location-rejected',
  LOCATION_NEEDS_MORE_INFO = './location-needs-more-info',
  DEPOSIT_CONFIRMED = './deposit-confirmed',
  BOOKING_APPROVED = './booking-approved',
  BOOKING_REJECTED = './booking-rejected',
  BOOKING_CANCELLED = './booking-cancelled',
  BOOKING_FORCE_CANCELLED = './booking-force-cancelled',
  EVENT_ATTENDANCE_REFUNDED = './event-attendance-refunded',
}

export const EmailSubjects = {
  [EmailTemplates.WELCOME]: 'Welcome to Urban Lens!',
  [EmailTemplates.CONFIRM_OTP]: 'Your OTP Code',
  [EmailTemplates.BUSINESS_APPROVED]: 'Business Application Approved!',
  [EmailTemplates.BUSINESS_REJECTED]: 'Business Application Update',
  [EmailTemplates.LOCATION_APPROVED]: 'Location Request Approved!',
  [EmailTemplates.LOCATION_REJECTED]: 'Location Request Rejected',
  [EmailTemplates.LOCATION_NEEDS_MORE_INFO]: 'Location Request Needs More Info',
  [EmailTemplates.DEPOSIT_CONFIRMED]: 'Deposit Confirmed',
  [EmailTemplates.BOOKING_APPROVED]: 'Booking Approved!',
  [EmailTemplates.BOOKING_REJECTED]: 'Booking Rejected',
  [EmailTemplates.BOOKING_CANCELLED]: 'Booking Cancelled',
  [EmailTemplates.BOOKING_FORCE_CANCELLED]: 'Booking Force Cancelled',
  [EmailTemplates.EVENT_ATTENDANCE_REFUNDED]: 'Event Attendance Refunded',
};
