export enum LocationBookingStatus {
  AWAITING_BUSINESS_PROCESSING = 'AWAITING_BUSINESS_PROCESSING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  EXPIRED_BEFORE_PAYMENT = 'EXPIRED_BEFORE_PAYMENT',
}
