export enum LocationRequestStatus {
  AUTO_VALIDATING = 'AUTO_VALIDATING',
  AWAITING_ADMIN_REVIEW = 'AWAITING_ADMIN_REVIEW',
  APPROVED = 'APPROVED',
  NEEDS_MORE_INFO = 'NEEDS_MORE_INFO',
  REJECTED = 'REJECTED',
  CANCELLED_BY_BUSINESS = 'CANCELLED_BY_BUSINESS',
}
