export enum ReportPenaltyActions {
  WARN_USER = 'WARN_USER',
  SUSPEND_ACCOUNT = 'SUSPEND_ACCOUNT',
  BAN_ACCOUNT = 'BAN_ACCOUNT',
  SUSPEND_LOCATION_BOOKING = 'SUSPEND_LOCATION_BOOKING',
  BAN_POST = 'BAN_POST',
}
