export enum ReportResolutionActions {
  NO_ACTION_TAKEN = 'NO_ACTION_TAKEN',
  MALICIOUS_REPORT = 'MALICIOUS_REPORT',
  ISSUE_APOLOGY = 'ISSUE_APOLOGY',
  REFUND_TICKET = 'REFUND_TICKET',
  REFUND_BOOKING = 'REFUND_BOOKING',
}
