export enum TagGroup {
  LOCATION_TYPE = 'LOCATION_TYPE', // cafe, restaurant, bar, park...
  EVENT_TYPE = 'EVENT_TYPE', // meetup, workshop, concert...
  USER_TYPE = 'USER_TYPE', // admin, moderator, regular...
}
