export enum TagGroup {
  LOCATION_TYPE = 'LOCATION_TYPE', // cafe, restaurant, bar, park...
  EVENT_TYPE = 'EVENT_TYPE', // meetup, workshop, concert...
  THEME = 'THEME', // tech, art, food...
  AESTHETIC = 'AESTHETIC', // minimalistic, vintage, modern... (meaning style or vibe)
  ACTIVITY = 'ACTIVITY', // live-music, coffee-tasting, board-games...
  OTHER = 'OTHER',
}
