export enum TransactionCategory {
  ORDER_PAYMENT = 'ORDER_PAYMENT',
  TICKET_REFUND = 'TICKET_REFUND',
  LOCATION_BOOKING_PAYOUT_BUSINESS = 'LOCATION_BOOKING_PAYOUT_BUSINESS',
  EVENT_PAYOUT_CREATOR = 'EVENT_PAYOUT_CREATOR',
  LOCATION_BOOKING_PAYOUT_SYSTEM = 'LOCATION_BOOKING_PAYOUT_SYSTEM',
  EVENT_PAYOUT_SYSTEM = 'EVENT_PAYOUT_SYSTEM',
  LOCATION_BOOKING_PAYMENT = 'LOCATION_BOOKING_PAYMENT',
  LOCATION_BOOKING_FORCE_CANCELLATION_FINE = 'LOCATION_BOOKING_FORCE_CANCELLATION_FINE',
  LOCATION_BOOKING_REFUND = 'LOCATION_BOOKING_REFUND',
  LOCATION_BOOKING_REJECTED = 'LOCATION_BOOKING_REJECTED',
}
