export enum WalletExternalTransactionAction {
  CREATE_DEPOSIT_TRANSACTION = 'CREATE_DEPOSIT_TRANSACTION',
  CONFIRM_DEPOSIT_TRANSACTION = 'CONFIRM_DEPOSIT_TRANSACTION',
  ADD_BALANCE_AFTER_DEPOSIT = 'ADD_BALANCE_AFTER_DEPOSIT',
  CREATE_WITHDRAW_AND_LOCK_FUNDS = 'CREATE_WITHDRAW_AND_LOCK_FUNDS',
  START_PROCESSING_WITHDRAW_TRANSACTION = 'START_PROCESSING_WITHDRAW_TRANSACTION',
  COMPLETE_PROCESSING_WITHDRAW_TRANSACTION = 'COMPLETE_PROCESSING_WITHDRAW_TRANSACTION',
  MARK_TRANSFER_FAILED = 'MARK_TRANSFER_FAILED',
  REJECT_WITHDRAW_TRANSACTION = 'REJECT_WITHDRAW_TRANSACTION',
  CANCEL_WITHDRAW_TRANSACTION = 'CANCEL_WITHDRAW_TRANSACTION',
  CANCEL_DEPOSIT_TRANSACTION = 'CANCEL_DEPOSIT_TRANSACTION',
}
