export enum WalletExternalTransactionAction {
  CREATE_DEPOSIT_TRANSACTION = 'CREATE_DEPOSIT_TRANSACTION',
  CONFIRM_DEPOSIT_TRANSACTION = 'CONFIRM_DEPOSIT_TRANSACTION',
  ADD_BALANCE_AFTER_DEPOSIT = 'ADD_BALANCE_AFTER_DEPOSIT',
}
