export enum WalletExternalTransactionAction {
  CREATE_DEPOSIT_TRANSACTION = 'CREATE_DEPOSIT_TRANSACTION',
  CONFIRM_DEPOSIT_TRANSACTION = 'CONFIRM_DEPOSIT_TRANSACTION',
  ADD_BALANCE_AFTER_DEPOSIT = 'ADD_BALANCE_AFTER_DEPOSIT',
  CREATE_WITHDRAW_AND_LOCK_FUNDS = 'CREATE_WITHDRAW_AND_LOCK_FUNDS',
  APPROVE_WITHDRAW_TRANSACTION = 'APPROVE_WITHDRAW_TRANSACTION',
}
